### ISSUE TITLE
How to apply to real dataset like tum rgbd data format? need help.

### ISSUE THREAD

**Issue by cdb0y511** [weders/RoutedFusion#11]
Hi, @weders , thanks for sharing your great works.
I want to use it on the real RGB-d dataset. For example, like tum RGB-D data.
And I also acquire some data from Intel realsense. 
The basic input is RGB and depth map, along with poses and intrinsic.
Could help me to make it work?
Thanks again.
Another question is how to retrain your routed model for specified sensors.

**Comment by weders** [comment]
Hi @cdb0y511, for better understanding of your problem: are you trying to fuse both appearance and geometry or are you trying to improve geometry with RGB information? 

For training for a specific sensor, ideally you collect real-world training data (e.g. with with the sensor you are interested in and an accurate LIDAR). However, this is probably a lot of work. Alternatively, you could estimate the noise statistics of your sensor and implement a noise simulator and train on synthetic data. First, you should train the routing network. Afterwards, you can use the pre-trained routing network and train the fusion network. 

I hope this helps!

Cheers!
