### ISSUE TITLE
3D Convolution for fusion model

### ISSUE THREAD

**Issue by rjtshrm** [weders/RoutedFusion#18]
Thanks for sharing such great work. During the fusion, I see you are using 2D Convolution with channels. As input to your network in D<sub>t</sub>, C<sub>t</sub>, W<sup>*</sup><sub>t-1</sub> and  V<sup>*</sup><sub>t-1</sub>. Since, both W<sup>*</sup><sub>t-1</sub> and  V<sup>*</sup><sub>t-1</sub> are 3-dimensional, isn't it good to use 3D Convolution rather than 2D convolution. I see you are using 2D convolution in fusion models and treat depth as channels.  May, I also know how long it took for you training the fusion model.

**Comment by weders** [comment]
Hi @rjtshrm 

We modeled the depth along the rays as channels as this fixes the position along the ray. If you use 3D convolutions, the same kernel is used for all different positions on the ray (depending on kernel size, stride, etc.). This destroys the positional information along the ray, which we saw is quite important. If you use a different architecture, you would need to add some positional encoding to the features (i.e. encode the position along the ray using PE). The fusion network takes roughly a day to converge.
