### ISSUE TITLE
Data preparation script issues.

### ISSUE THREAD

**Issue by mpottinger** [weders/RoutedFusion#21]
Hello, I am just wondering if anyone else is finding it impossible to prepare the ShapeNet data now, i've run into a brick wall with meshlabserver, which seems to crash when attempting to run the "simplification.mlx" meshlab script. It seems meshlab in its current state can not run scripts at all. I have tried on different computers, different os's, I've tried scripts other than the ones included in this repo. On PC (Linux and Windows), and Mac, etc. All the same. running a script will segfault. Tried older versions of meshlab, same result. So I am wondering how this ever was made to work, when meshlab seems broken. I tried bypassing the simplification script and making it into just a straight copy of the mesh, and that appears to work, but now I have an issue with binvox not working on wsl2 (not part of this issue, but haven't seen the result of skipping mesh simplification step). Is the mesh simplification essential? It seems this meshlab issue is insurmountable without a fix in meshlab itself. 

Also during dependency install libgfortran was giving an error (unable to find version). I fixed that by removing the version # from environment.yml.

**Comment by mpottinger** [comment]
Ok after a long night and day working on this I have dependencies install and the conversion script running. Changes needed to be made to some of the files in order to get it to work.

1. libgfortran version had to be changed
2. disable pbuffers on binvox arguments (remove -pb)
3. deps/mesh-fusion/3_simplify.py had to be modified to not use mlx scripting and instead use pymeshlab instead of meshlabserver. used the options from simplification.mlx in a call to the filter in pymeshlab

The section that runs the filter in 3_simplify.py changed like this:

`for filepath in files:
            #os.system('meshlabserver -i %s -o %s -s %s' % (
            #    filepath,
            #    os.path.join(self.options.out_dir, ntpath.basename(filepath)),
            #    self.simplification_script
            #))

            ms = pymeshlab.MeshSet()
            ms.load_new_mesh(filepath)
            
            ms.simplification_quadric_edge_collapse_decimation(targetfacenum=5000,targetperc=0,qualitythr=0.5,preserveboundary=False,boundaryweight=1,
            	preservenormal=True,preservetopology=False,optimalplacement=True,planarquadric=True,planarweight=0.001,qualityweight=False,autoclean=True,selected=False)
            	
            ms.save_current_mesh(os.path.join(self.options.out_dir, ntpath.basename(filepath)))`


Now I can finally convert the data and try this out!

That's just how these things work! lol, version hell and breakage is always there, very common for me to struggle with.

**Comment by BoomFan** [comment]
> 

You are such a lifesaver!! Thank you very much!

I followed your instructions and finally get it to work!

1, `libgfortran-ng=7.5.0`
2, I'm on Linux, my code still works even with the pbuffers
3, I followed your instructions to modify the `deps/mesh-fusion/3_simplify.py` file. And also `import pymeshlab`
