### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by talkenig** [weders/RoutedFusion#3]
First, thanks for sharing the code for this great work.
I installed everything and was able to run successfully test_fusion. I saw the output files .volume.hf5 and .weights.hf5 but not sure how to visualize the results. I assume I need to load only the volume files and run marching cubes on those, but as I mentioned - not sure. Would appreciate very much if you could share a code snippet for visulaization.

**Comment by MingwuZheng** [comment]
You can just extract negative values to get a point cloud.

**Comment by talkenig** [comment]
Thanks for the quick response. So I get that the volume file is indeed the tsdf, taking the negative values would give me all points inside the shape and running marching cubes with a zero threshold will give the object mesh. Is that right or did I miss something?

**Comment by MingwuZheng** [comment]
Yes, but I'm not sure whether it is the best way to get an object mesh. As far as I know, marching cubes is enough for the current test case.

**Comment by weders** [comment]
Hi @talkenig,

thanks for your interest in RoutedFusion!

The following code snippet should allow you to extract and visualize the mesh from a .volume.hf5 file. Alternatively, you can also use another visualization tool (e.g. Open3D).

You need to check if ```tsdf``` has the correct shape and number of dimensions.

```
import h5py
from graphics.utils import extract_mesh_marching_cubes
from graphics.visualization import plot_mesh

file = os.path.join(path_to_your_file, 'xyz.volume.hf5')

with h5py.File(file, 'r') as hf:
    tsdf = hf['TSDF'][:]

mesh = extract_mesh_marching_cubes(tsdf)
plot_mesh(mesh)
```

Cheers!
