### ISSUE TITLE
Can provided pretrained model be used on Kinect2 datasets?

### ISSUE THREAD

**Issue by MingwuZheng** [weders/RoutedFusion#5]
Hi, firstly thanks for your great work again.
Recently I noticed that your provided model are trained by 320*240 depth maps, which are rendered from ShapeNet models. Should all depth maps be downsampled to this resolution if I want perform RoutedFusion with your pretrained model?

**Comment by weders** [comment]
Hi @MingwuZheng,

Sorry for the late reply. 

Technically, the pre-trained models can be used for KinectV2. However, you need to downsample the depth maps in that case. Depending on the range of the depth values you encounter in your use case, I suggest you train a new model (especially the routing network). 

Cheers!

**Comment by MingwuZheng** [comment]
> Hi @MingwuZheng,
> 
> Sorry for the late reply.
> 
> Technically, the pre-trained models can be used for KinectV2. However, you need to downsample the depth maps in that case. Depending on the range of the depth values you encounter in your use case, I suggest you train a new model (especially the routing network).
> 
> Cheers!

Thanks for your reply!
When using pretrained model, I've tried to change some key parameters such as resolution and boundingbox to avoid doing downsampling and losing information. Amazingly it can still work well! Before I train my own model, I have a few questions:
-Is OpenGL-based depth map rendering method(meshfusion) necessary? Since meshfusion is hard to deploy and not stable in our linux servers, can I directly caculate depth maps using intrinsics and extrinsics?
-RoutedFusion only seems to run in real time with **128** resolution.  Is it normal or have I done something wrong? 
-Can man-made noise function fully represent real depth sensor noise?
Looking forward to your reply.

**Comment by weders** [comment]
1) If you have depth-maps and corresponding 3D ground-truth, you do not need any rendering. RoutedFusion assumes you have those and does not provide any depth rendering capabilities.

2) I was notified that there is a problem with GPU allocation in the integrator, which slows the pipeline down. It's a small bug but I have not found the time to fix it yet. 

3) No, a man-made noise function is always an approximation to some degree. If you really want to capture the real noise distribution, I recommend you collect a data set with a Kinect and an accurate laser scan as ground-truth.

**Comment by MingwuZheng** [comment]
Thanks！
