### ISSUE TITLE
Is the default yaml and data class for Burghers available

### ISSUE THREAD

**Issue by ZikeYan** [weders/RoutedFusion#8]
Hi, thanks for sharing the code for this great work
I wonder if you can provide your default setting and the dataset class for burghers dataset so I can make a fair comparison with your method?

**Comment by ZikeYan** [comment]
> Hi, thanks for sharing the code for this great work
> I wonder if you can provide your default setting and the dataset class for burghers dataset so I can make a fair comparison with your method?

Here is the result I ran on ICL-NUIM dataset. Only a small portion of the scene is generated, and the scale is much larger than the groundtruth file. I am not quite familiar with the learning based methods. Is it due to the .binvox generation? 
![Screenshot from 2020-11-10 01-38-03副本](https://user-images.githubusercontent.com/28919685/98577181-872b6780-22f6-11eb-97dc-cc62d4595495.png)

**Comment by cdb0y511** [comment]
> h file. I am

Hi, have you solved this problem? 
How do you modify ICL-NUIM as input? I think the pre-trained model is based on ShapeNet 320*240.
#5 
Thanks.
