### ISSUE TITLE
Burghers scene reconstruction artifacts

### ISSUE THREAD

**Issue by vadimselyutin** [weders/RoutedFusion#9]
Hi! Thanks again for your great work and its code release.

Currently I’m trying to run RoutedFusion on the burghers scene from the 3D Scene Data. For that purpose I created my own test config file, test txt list and a new dataset class, where I use the same sample preprocessing as you, except for inverting extrinsics matrix. In database class I manually set bbox and scenes_gt_resolution. After that I’m able to calculate needed sample['origin'] and volume shape using bbox coordinates.

I use your extract_mesh_marching_cubes function from graphics module to get a mesh from .h5 file, so that I can save it as a .ply file and visualize it. When I ran your pretrained model on burghers_sample (first 500 pictures) I obtained quite a smooth result.

![image](https://user-images.githubusercontent.com/37964075/99831409-0f6c0100-2b70-11eb-8d9f-8f66c9561261.png)

But when I tried to reproduce the results from your article on two other statues (6500-8500th and 5000-7000th pictures) I got some strange artifacts. What could be the possible reason for such behavior?

Thank you in advance!

![image](https://user-images.githubusercontent.com/37964075/99831517-3fb39f80-2b70-11eb-9f3d-c4f31741374b.png)
![image](https://user-images.githubusercontent.com/37964075/99831533-47734400-2b70-11eb-9fa4-22059008fb58.png)
![image](https://user-images.githubusercontent.com/37964075/99831540-4a6e3480-2b70-11eb-8f26-20cfa6c9ff1a.png)
![image](https://user-images.githubusercontent.com/37964075/99831553-4e01bb80-2b70-11eb-8066-9d3037319956.png)
![image](https://user-images.githubusercontent.com/37964075/99831611-64a81280-2b70-11eb-969f-5675f16edf94.png)

**Comment by weders** [comment]
Hi @vadimselyutin, 

Thanks for your message!

I remember these artefacts from this scene. There are some frames wich are quite off somehow. You get rid of these artefacts by clipping the depth values you fuse at around 1.9m. I also suggest to retrain the routing network on a slightly higher noise level than the pretrained model (e.g. 0.01 or 0.03). I hope this helps. If I find time, I might upload the original dataset class in the next days. 

Cheers!

**Comment by fengziyue** [comment]
Hi @weders @vadimselyutin :

Thank you for the fantastic work, I'm interested in reproducing the results on some real-world datasets, could you share the code for the `3D Scene`, `7-Scenes`, or other real-world datasets?

Any information would be greatly appreciated, thank you!
